<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>3.0.0</Version>
    <PackageVersion>3.0.0</PackageVersion>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <FileVersion>3.0.0.0</FileVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PackageId>Gulla.Episerver.AutomaticImageDescription.ScheduledJob</PackageId>
    <Title>Gulla.Episerver.AutomaticImageDescription.ScheduledJob</Title>
    <Authors>Tomas Hensrud Gulla</Authors>
    <Description>A scheduled job that automatically populate properties based on image content.</Description>
    <PackageTags>Optimizely Episerver Images</PackageTags>
    <PackageProjectUrl>https://github.com/tomahg/Gulla.Episerver.AutomaticImageDescription/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/tomahg/Gulla.Episerver.AutomaticImageDescription/</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>Update to .NET 10 and add support for CMS 13</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Gulla.Episerver.AutomaticImageDescription" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPiServer.CMS.Core" Version="[13.0.0, 14.0.0)" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>